#!/usr/bin/env bash
#
# build-wasm.sh — build the Hemlock WASM interpreter for browser execution.
#
# The playground's "Browser" execution mode runs the Hemlock interpreter
# entirely client-side via WebAssembly. That needs two build artifacts:
#
#   wasm/hemlock.js     Emscripten JS loader glue
#   wasm/hemlock.wasm   the interpreter compiled to WebAssembly
#
# These are generated from the hemlang/hemlock source tree (target
# `make wasm-interpreter`) and copied here. The small JS wrapper
# (wasm/hemlock-api.js) and pre-init shim (wasm/pre.js) are committed to
# this repo; the .js/.wasm artifacts are regenerated by this script.
#
# Requirements:
#   - Emscripten SDK on PATH (emcc). See https://emscripten.org/docs/getting_started/downloads.html
#   - A checkout of hemlang/hemlock (cloned automatically if missing)
#
# Usage:
#   ./build-wasm.sh                 # clone/build hemlock, copy artifacts
#   HEMLOCK_DIR=/path/to/hemlock ./build-wasm.sh   # use an existing checkout
#
set -euo pipefail

PLAYGROUND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HEMLOCK_DIR="${HEMLOCK_DIR:-$PLAYGROUND_DIR/../hemlock}"
HEMLOCK_REPO="${HEMLOCK_REPO:-https://github.com/hemlang/hemlock.git}"

echo "==> Hemlock WASM build"
echo "    playground: $PLAYGROUND_DIR"
echo "    hemlock:    $HEMLOCK_DIR"

if ! command -v emcc >/dev/null 2>&1; then
    echo "ERROR: emcc (Emscripten) not found on PATH." >&2
    echo "       Install the Emscripten SDK and 'source emsdk_env.sh', then retry." >&2
    echo "       https://emscripten.org/docs/getting_started/downloads.html" >&2
    exit 1
fi

if [ ! -d "$HEMLOCK_DIR" ]; then
    echo "==> Cloning hemlock into $HEMLOCK_DIR"
    git clone --depth 1 "$HEMLOCK_REPO" "$HEMLOCK_DIR"
fi

echo "==> Building wasm-interpreter (this can take a few minutes)"
make -C "$HEMLOCK_DIR" wasm-interpreter

echo "==> Copying artifacts into $PLAYGROUND_DIR/wasm/"
mkdir -p "$PLAYGROUND_DIR/wasm"
cp "$HEMLOCK_DIR/wasm/hemlock.js"      "$PLAYGROUND_DIR/wasm/hemlock.js"
cp "$HEMLOCK_DIR/wasm/hemlock.wasm"    "$PLAYGROUND_DIR/wasm/hemlock.wasm"
# Refresh the wrapper too, in case the upstream API changed.
cp "$HEMLOCK_DIR/wasm/hemlock-api.js"  "$PLAYGROUND_DIR/wasm/hemlock-api.js"
cp "$HEMLOCK_DIR/wasm/pre.js"          "$PLAYGROUND_DIR/wasm/pre.js"

echo "==> Done. Artifacts:"
ls -lh "$PLAYGROUND_DIR/wasm/"
echo
echo "Open playground.html and switch the toolbar toggle to 'Browser' to run"
echo "Hemlock entirely in the browser (no Grove server required)."
